"""add international holding document vault

Revision ID: 00195c0cd789
Revises: 1c64174a5456
Create Date: 2026-09-30 07:03:21.399034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00195c0cd789'
down_revision = '1c64174a5456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_holding_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('iv', sa.String(length=64), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_holding_document', schema=None) as batch_op:
        batch_op.create_index('ix_intl_doc_holding', ['holding_id'], unique=False)
        batch_op.create_index('ix_intl_doc_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_holding_document', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_doc_user')
        batch_op.drop_index('ix_intl_doc_holding')

    op.drop_table('international_holding_document')
    # ### end Alembic commands ###
