"""add net worth international field and holding nominees

Revision ID: 1c64174a5456
Revises: 9b3f8c35087d
Create Date: 2026-09-28 03:09:14.090277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c64174a5456'
down_revision = '9b3f8c35087d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_holding_nominee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_holding_nominee', schema=None) as batch_op:
        batch_op.create_index('ix_intl_holding_nominee_holding', ['holding_id'], unique=False)

    with op.batch_alter_table('net_worth_history', schema=None) as batch_op:
        # server_default='0' (not left as the autogenerated nullable=True
        # with no default) so every pre-existing NetWorthHistory row
        # reads as 0.0 rather than NULL for this new column — matches
        # this table's "immutable history, but no column should ever
        # read as a surprise NULL" convention (every other column here
        # has default=0 at the model level too).
        batch_op.add_column(sa.Column('international', sa.Float(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('net_worth_history', schema=None) as batch_op:
        batch_op.drop_column('international')

    with op.batch_alter_table('international_holding_nominee', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_holding_nominee_holding')

    op.drop_table('international_holding_nominee')
    # ### end Alembic commands ###
