"""add rsu espp vesting tranches

Revision ID: 2c6ca6024064
Revises: 926cd281d6d6
Create Date: 2026-09-30 07:45:50.238078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6ca6024064'
down_revision = '926cd281d6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_vesting_tranche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=10), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vest_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('fmv_native', sa.Float(), nullable=False),
    sa.Column('purchase_price_native', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_vesting_tranche', schema=None) as batch_op:
        batch_op.create_index('ix_intl_vesting_holding', ['holding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_vesting_tranche', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_vesting_holding')

    op.drop_table('international_vesting_tranche')
    # ### end Alembic commands ###
