"""add password reset token and mf nav_updated_at fields

Revision ID: 4f84d2cfe8e1
Revises: cf5865345df0
Create Date: 2026-09-27 10:23:22.063057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f84d2cfe8e1'
down_revision = 'cf5865345df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mutual_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token_hash')

    with op.batch_alter_table('mutual_fund', schema=None) as batch_op:
        batch_op.drop_column('nav_updated_at')

    # ### end Alembic commands ###
