"""add 2FA and session management tables

Revision ID: 703352c8fbd8
Revises: c6210286120d
Create Date: 2026-09-27 15:23:19.049246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703352c8fbd8'
down_revision = 'c6210286120d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=256), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_session_token'), ['session_token'], unique=True)

    # totp_enabled is NOT NULL with only a Python-level model default —
    # existing rows need a server_default to backfill against, same
    # pattern used for notify_monthly_summary/display_currency etc.
    # Dropped again below so future inserts rely on the model-level
    # default (every existing/new account starts with 2FA off).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('totp_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_session_token'))

    op.drop_table('user_session')
    op.drop_table('backup_code')
    # ### end Alembic commands ###
