"""add tcs and dividend withholding tracking

Revision ID: 926cd281d6d6
Revises: 00195c0cd789
Create Date: 2026-09-30 07:31:47.005137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926cd281d6d6'
down_revision = '00195c0cd789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted by hand: tcs_amount_inr is NOT NULL, so existing rows
    # need a server-side default (0.0 — no TCS on remittances logged
    # before this batch existed) for the ALTER to succeed against a
    # table that already has data, matching the pattern used whenever
    # a NOT NULL column is added to an existing table elsewhere in
    # this project's migrations. Dropped again in server_default=None
    # right after, so the column doesn't advertise a DB-level default
    # to future schema readers -- new rows go through
    # services._compute_tcs()/add_remittance(), which always supplies
    # an explicit value.
    with op.batch_alter_table('international_remittance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tcs_amount_inr', sa.Float(), nullable=False, server_default='0'))
        batch_op.alter_column('tcs_amount_inr', server_default=None)

    with op.batch_alter_table('international_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gross_amount_native', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_withheld_native', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_transaction', schema=None) as batch_op:
        batch_op.drop_column('tax_withheld_native')
        batch_op.drop_column('gross_amount_native')

    with op.batch_alter_table('international_remittance', schema=None) as batch_op:
        batch_op.drop_column('tcs_amount_inr')

    # ### end Alembic commands ###
