"""add international investing centre tables

Revision ID: 9b3f8c35087d
Revises: 703352c8fbd8
Create Date: 2026-09-28 02:32:00.147501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3f8c35087d'
down_revision = '703352c8fbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('broker_or_institution', sa.String(length=200), nullable=True),
    sa.Column('account_number_masked', sa.String(length=50), nullable=True),
    sa.Column('native_currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('avg_cost_native', sa.Float(), nullable=True),
    sa.Column('live_price_native', sa.Float(), nullable=True),
    sa.Column('current_value_native', sa.Float(), nullable=False),
    sa.Column('usd_value', sa.Float(), nullable=False),
    sa.Column('fx_rate_used', sa.Float(), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('invested_native', sa.Float(), nullable=True),
    sa.Column('xirr', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_holding', schema=None) as batch_op:
        batch_op.create_index('ix_intl_holding_user_archived', ['user_id', 'archived'], unique=False)

    op.create_table('international_remittance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_inr', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('fx_rate_used', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('remitting_bank', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('international_remittance', schema=None) as batch_op:
        batch_op.create_index('ix_intl_remit_user_date', ['user_id', 'date'], unique=False)

    op.create_table('international_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price_native', sa.Float(), nullable=True),
    sa.Column('amount_native', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international_value_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usd_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['international_holding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_id', 'date', name='uq_intl_snapshot_holding_date')
    )
    with op.batch_alter_table('international_value_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_intl_snapshot_holding_date', ['holding_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('international_value_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_snapshot_holding_date')

    op.drop_table('international_value_snapshot')
    op.drop_table('international_transaction')
    with op.batch_alter_table('international_remittance', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_remit_user_date')

    op.drop_table('international_remittance')
    with op.batch_alter_table('international_holding', schema=None) as batch_op:
        batch_op.drop_index('ix_intl_holding_user_archived')

    op.drop_table('international_holding')
    # ### end Alembic commands ###
