"""add multi-currency fields to wealth asset and liability

Revision ID: a2fec04467cf
Revises: 4f84d2cfe8e1
Create Date: 2026-09-27 12:12:48.976069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fec04467cf'
down_revision = '4f84d2cfe8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted by hand: ###
    # `currency` is NOT NULL with a Python-level model default ("INR"),
    # which SQLAlchemy only applies on INSERT, never on this ALTER TABLE
    # — every existing row would get a NULL and violate the NOT NULL
    # constraint the moment this runs. A server_default backfills every
    # existing asset/liability as INR (the correct, safe assumption:
    # every row until now WAS an INR value with no other currency ever
    # recorded), and is then dropped so future inserts rely on the
    # model-level default instead, same convention as the rest of this
    # app's Alembic migrations.
    with op.batch_alter_table('wealth_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='INR'))
        batch_op.add_column(sa.Column('foreign_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_date', sa.Date(), nullable=True))

    with op.batch_alter_table('wealth_liability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False, server_default='INR'))
        batch_op.add_column(sa.Column('foreign_outstanding_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fx_rate_date', sa.Date(), nullable=True))

    with op.batch_alter_table('wealth_asset', schema=None) as batch_op:
        batch_op.alter_column('currency', server_default=None)

    with op.batch_alter_table('wealth_liability', schema=None) as batch_op:
        batch_op.alter_column('currency', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wealth_liability', schema=None) as batch_op:
        batch_op.drop_column('fx_rate_date')
        batch_op.drop_column('fx_rate')
        batch_op.drop_column('foreign_outstanding_amount')
        batch_op.drop_column('currency')

    with op.batch_alter_table('wealth_asset', schema=None) as batch_op:
        batch_op.drop_column('fx_rate_date')
        batch_op.drop_column('fx_rate')
        batch_op.drop_column('foreign_value')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
