"""add global display currency and fx rate cache

Revision ID: b53588e2c184
Revises: a2fec04467cf
Create Date: 2026-09-27 14:04:37.691538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53588e2c184'
down_revision = 'a2fec04467cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted by hand: ###
    # display_currency is NOT NULL with a Python-level model default
    # ("INR"), which only applies on INSERT — every existing user row
    # needs a server_default here so this ALTER TABLE doesn't try to
    # write NULL into a NOT NULL column. Every existing user has only
    # ever seen INR everywhere in the app, so INR is the correct
    # backfill, not a guess. Dropped again after backfilling so future
    # inserts rely on the model-level default, matching this project's
    # established convention (see the multi-currency migration).
    op.create_table('fx_rate_cache',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('currency')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_currency', sa.String(length=3), nullable=False, server_default='INR'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('display_currency', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('display_currency')

    op.drop_table('fx_rate_cache')
    # ### end Alembic commands ###
