"""add notification preferences and notification log

Revision ID: c6210286120d
Revises: b53588e2c184
Create Date: 2026-09-27 14:44:29.404277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6210286120d'
down_revision = 'b53588e2c184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notif_type', sa.String(length=30), nullable=False),
    sa.Column('ref_key', sa.String(length=120), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notif_type', 'ref_key', name='uq_notification_log_user_type_ref')
    )
    # Both new columns are NOT NULL with only a Python-level model
    # default — existing rows need a server_default to backfill against,
    # same pattern used for display_currency/wealth foreign-currency
    # columns in earlier migrations. Dropped again below so future
    # inserts rely on the model-level default (both start OFF/False).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_monthly_summary', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('notify_renewal_sip_reminders', sa.Boolean(),
                                       nullable=False, server_default=sa.false()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('notify_monthly_summary', server_default=None)
        batch_op.alter_column('notify_renewal_sip_reminders', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_renewal_sip_reminders')
        batch_op.drop_column('notify_monthly_summary')

    op.drop_table('notification_log')
    # ### end Alembic commands ###
