"""baseline schema

Revision ID: cf5865345df0
Revises: 
Create Date: 2026-09-23 09:50:38.190724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5865345df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('encryption_salt', sa.String(length=64), nullable=True),
    sa.Column('encryption_verifier', sa.Text(), nullable=True),
    sa.Column('encryption_verifier_iv', sa.String(length=64), nullable=True),
    sa.Column('encryption_enabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cashflow_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'year', 'month', name='uq_cf_budget_user_category_month')
    )
    with op.batch_alter_table('cashflow_budget', schema=None) as batch_op:
        batch_op.create_index('ix_cf_budget_user_month', ['user_id', 'year', 'month'], unique=False)

    op.create_table('cashflow_recurring_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_recurring_payment', schema=None) as batch_op:
        batch_op.create_index('ix_cf_recurring_user_active', ['user_id', 'active'], unique=False)

    op.create_table('cashflow_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_cf_txn_user_date', ['user_id', 'date'], unique=False)

    op.create_table('family_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=100), nullable=True),
    sa.Column('guardian_contact', sa.String(length=100), nullable=True),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.Column('parent_family_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_family_person_id'], ['family_person.id'], ),
    sa.ForeignKeyConstraint(['spouse_id'], ['family_person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_timeline', schema=None) as batch_op:
        batch_op.create_index('ix_fam_timeline_user', ['user_id'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('target_amt', sa.Float(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('current_savings', sa.Float(), nullable=True),
    sa.Column('monthly_sip', sa.Float(), nullable=True),
    sa.Column('annual_return', sa.Float(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('step_up_pct', sa.Float(), nullable=True),
    sa.Column('glide_start_equity_pct', sa.Float(), nullable=True),
    sa.Column('glide_end_equity_pct', sa.Float(), nullable=True),
    sa.Column('is_retirement_goal', sa.Boolean(), nullable=True),
    sa.Column('retirement_age', sa.Integer(), nullable=True),
    sa.Column('life_expectancy', sa.Integer(), nullable=True),
    sa.Column('monthly_expense_today', sa.Float(), nullable=True),
    sa.Column('expense_inflation_pct', sa.Float(), nullable=True),
    sa.Column('post_retirement_return_pct', sa.Float(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('insurance_type', sa.String(length=100), nullable=False),
    sa.Column('custom_type', sa.String(length=200), nullable=True),
    sa.Column('insurer', sa.String(length=200), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('policy_holder', sa.String(length=200), nullable=True),
    sa.Column('sum_assured', sa.Float(), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('premium_frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('next_premium_due', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('agent_contact', sa.String(length=50), nullable=True),
    sa.Column('cashless_available', sa.String(length=5), nullable=True),
    sa.Column('claim_history', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('policy_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('property_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archived_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.create_index('ix_ins_policy_archived', ['is_archived'], unique=False)
        batch_op.create_index('ix_ins_policy_category', ['category'], unique=False)
        batch_op.create_index('ix_ins_policy_number', ['user_id', 'policy_number'], unique=False)
        batch_op.create_index('ix_ins_policy_renewal', ['renewal_date'], unique=False)
        batch_op.create_index('ix_ins_policy_user', ['user_id'], unique=False)

    op.create_table('mutual_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('amc', sa.String(length=200), nullable=True),
    sa.Column('scheme', sa.String(length=300), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('amfi_code', sa.String(length=20), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('invested', sa.Float(), nullable=True),
    sa.Column('xirr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('net_worth_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('gold', sa.Float(), nullable=True),
    sa.Column('realestate', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('other', sa.Float(), nullable=True),
    sa.Column('liabilities', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_user_snapshot_date')
    )
    op.create_table('retirement_scheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheme_type', sa.String(length=60), nullable=False),
    sa.Column('custom_type', sa.String(length=200), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('balance_updated_at', sa.Date(), nullable=True),
    sa.Column('growth_method', sa.String(length=30), nullable=False),
    sa.Column('rate_or_return_assumption', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('uan_number', sa.String(length=30), nullable=True),
    sa.Column('basic_salary', sa.Float(), nullable=True),
    sa.Column('employee_contribution_pct', sa.Float(), nullable=True),
    sa.Column('employer_contribution_pct', sa.Float(), nullable=True),
    sa.Column('target_retirement_year', sa.Integer(), nullable=True),
    sa.Column('extension_opted', sa.Boolean(), nullable=True),
    sa.Column('girl_child_name', sa.String(length=200), nullable=True),
    sa.Column('girl_child_dob', sa.Date(), nullable=True),
    sa.Column('pran_number', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('contribution_preference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retirement_scheme', schema=None) as batch_op:
        batch_op.create_index('ix_ret_scheme_status', ['status'], unique=False)
        batch_op.create_index('ix_ret_scheme_type', ['scheme_type'], unique=False)
        batch_op.create_index('ix_ret_scheme_user', ['user_id'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('live_price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('invested', sa.Float(), nullable=True),
    sa.Column('xirr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wealth_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('value_as_of', sa.Date(), nullable=True),
    sa.Column('ownership_type', sa.String(length=30), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('original_owner', sa.String(length=200), nullable=True),
    sa.Column('original_owner_relationship', sa.String(length=100), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_value', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('property_address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=True),
    sa.Column('metal_type', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('account_reference', sa.String(length=100), nullable=True),
    sa.Column('deposit_type', sa.String(length=50), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_asset', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_asset_status', ['status'], unique=False)
        batch_op.create_index('ix_wealth_asset_user', ['user_id'], unique=False)

    op.create_table('wealth_liability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('liability_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lender', sa.String(length=200), nullable=True),
    sa.Column('account_reference', sa.String(length=100), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('balance_as_of', sa.Date(), nullable=True),
    sa.Column('ownership_type', sa.String(length=30), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_liability', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_liability_status', ['status'], unique=False)
        batch_op.create_index('ix_wealth_liability_user', ['user_id'], unique=False)

    op.create_table('wealth_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_asset_value', sa.Float(), nullable=False),
    sa.Column('attributable_asset_value', sa.Float(), nullable=False),
    sa.Column('total_liability_value', sa.Float(), nullable=False),
    sa.Column('attributable_liability_value', sa.Float(), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_wealth_snapshot_user_date')
    )
    with op.batch_alter_table('wealth_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_snapshot_user_date', ['user_id', 'snapshot_date'], unique=False)

    op.create_table('wealth_value_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_value_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_snapshot_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('goal_holding_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('holding_type', sa.String(length=30), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=True),
    sa.Column('asset_class', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_addon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('addon_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_addon', schema=None) as batch_op:
        batch_op.create_index('ix_ins_addon_policy', ['policy_id'], unique=False)

    op.create_table('insurance_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_document', schema=None) as batch_op:
        batch_op.create_index('ix_ins_doc_policy', ['policy_id'], unique=False)
        batch_op.create_index('ix_ins_doc_user', ['user_id'], unique=False)

    op.create_table('insurance_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_member', schema=None) as batch_op:
        batch_op.create_index('ix_ins_member_policy', ['policy_id'], unique=False)

    op.create_table('insurance_nominee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_nominee', schema=None) as batch_op:
        batch_op.create_index('ix_ins_nominee_policy', ['policy_id'], unique=False)

    op.create_table('insurance_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_timeline', schema=None) as batch_op:
        batch_op.create_index('ix_ins_timeline_policy', ['policy_id'], unique=False)

    op.create_table('mutual_fund_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mutual_fund_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('scheme', sa.String(length=300), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('balance_units', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mutual_fund_id'], ['mutual_fund.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retirement_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['retirement_scheme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retirement_contribution', schema=None) as batch_op:
        batch_op.create_index('ix_ret_contrib_date', ['contribution_date'], unique=False)
        batch_op.create_index('ix_ret_contrib_scheme', ['scheme_id'], unique=False)

    op.create_table('retirement_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('iv', sa.String(length=64), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['retirement_scheme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retirement_document', schema=None) as batch_op:
        batch_op.create_index('ix_ret_doc_scheme', ['scheme_id'], unique=False)
        batch_op.create_index('ix_ret_doc_user', ['user_id'], unique=False)

    op.create_table('retirement_scheme_nominee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['retirement_scheme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retirement_scheme_nominee', schema=None) as batch_op:
        batch_op.create_index('ix_ret_nominee_scheme', ['scheme_id'], unique=False)

    op.create_table('retirement_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['retirement_scheme.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retirement_timeline', schema=None) as batch_op:
        batch_op.create_index('ix_ret_timeline_scheme', ['scheme_id'], unique=False)

    op.create_table('stock_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealth_asset_heir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['wealth_asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_asset_heir', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_asset_heir_asset', ['asset_id'], unique=False)

    op.create_table('wealth_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('liability_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('iv', sa.String(length=64), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['wealth_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['liability_id'], ['wealth_liability.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wealth_document', schema=None) as batch_op:
        batch_op.create_index('ix_wealth_doc_asset', ['asset_id'], unique=False)
        batch_op.create_index('ix_wealth_doc_liability', ['liability_id'], unique=False)
        batch_op.create_index('ix_wealth_doc_type', ['document_type'], unique=False)
        batch_op.create_index('ix_wealth_doc_uploaded', ['uploaded_at'], unique=False)
        batch_op.create_index('ix_wealth_doc_user', ['user_id'], unique=False)

    op.create_table('wealth_snapshot_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['wealth_snapshot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wealth_snapshot_log')
    with op.batch_alter_table('wealth_document', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_doc_user')
        batch_op.drop_index('ix_wealth_doc_uploaded')
        batch_op.drop_index('ix_wealth_doc_type')
        batch_op.drop_index('ix_wealth_doc_liability')
        batch_op.drop_index('ix_wealth_doc_asset')

    op.drop_table('wealth_document')
    with op.batch_alter_table('wealth_asset_heir', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_asset_heir_asset')

    op.drop_table('wealth_asset_heir')
    op.drop_table('stock_transaction')
    with op.batch_alter_table('retirement_timeline', schema=None) as batch_op:
        batch_op.drop_index('ix_ret_timeline_scheme')

    op.drop_table('retirement_timeline')
    with op.batch_alter_table('retirement_scheme_nominee', schema=None) as batch_op:
        batch_op.drop_index('ix_ret_nominee_scheme')

    op.drop_table('retirement_scheme_nominee')
    with op.batch_alter_table('retirement_document', schema=None) as batch_op:
        batch_op.drop_index('ix_ret_doc_user')
        batch_op.drop_index('ix_ret_doc_scheme')

    op.drop_table('retirement_document')
    with op.batch_alter_table('retirement_contribution', schema=None) as batch_op:
        batch_op.drop_index('ix_ret_contrib_scheme')
        batch_op.drop_index('ix_ret_contrib_date')

    op.drop_table('retirement_contribution')
    op.drop_table('mutual_fund_transaction')
    with op.batch_alter_table('insurance_timeline', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_timeline_policy')

    op.drop_table('insurance_timeline')
    with op.batch_alter_table('insurance_nominee', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_nominee_policy')

    op.drop_table('insurance_nominee')
    with op.batch_alter_table('insurance_member', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_member_policy')

    op.drop_table('insurance_member')
    with op.batch_alter_table('insurance_document', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_doc_user')
        batch_op.drop_index('ix_ins_doc_policy')

    op.drop_table('insurance_document')
    with op.batch_alter_table('insurance_addon', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_addon_policy')

    op.drop_table('insurance_addon')
    op.drop_table('goal_holding_link')
    with op.batch_alter_table('wealth_value_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_snapshot_entity')

    op.drop_table('wealth_value_snapshot')
    with op.batch_alter_table('wealth_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_snapshot_user_date')

    op.drop_table('wealth_snapshot')
    with op.batch_alter_table('wealth_liability', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_liability_user')
        batch_op.drop_index('ix_wealth_liability_status')

    op.drop_table('wealth_liability')
    with op.batch_alter_table('wealth_asset', schema=None) as batch_op:
        batch_op.drop_index('ix_wealth_asset_user')
        batch_op.drop_index('ix_wealth_asset_status')

    op.drop_table('wealth_asset')
    op.drop_table('user_profile')
    op.drop_table('stock')
    with op.batch_alter_table('retirement_scheme', schema=None) as batch_op:
        batch_op.drop_index('ix_ret_scheme_user')
        batch_op.drop_index('ix_ret_scheme_type')
        batch_op.drop_index('ix_ret_scheme_status')

    op.drop_table('retirement_scheme')
    op.drop_table('net_worth_history')
    op.drop_table('mutual_fund')
    with op.batch_alter_table('insurance_policy', schema=None) as batch_op:
        batch_op.drop_index('ix_ins_policy_user')
        batch_op.drop_index('ix_ins_policy_renewal')
        batch_op.drop_index('ix_ins_policy_number')
        batch_op.drop_index('ix_ins_policy_category')
        batch_op.drop_index('ix_ins_policy_archived')

    op.drop_table('insurance_policy')
    op.drop_table('goal')
    with op.batch_alter_table('family_timeline', schema=None) as batch_op:
        batch_op.drop_index('ix_fam_timeline_user')

    op.drop_table('family_timeline')
    op.drop_table('family_person')
    with op.batch_alter_table('cashflow_transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_cf_txn_user_date')

    op.drop_table('cashflow_transaction')
    with op.batch_alter_table('cashflow_recurring_payment', schema=None) as batch_op:
        batch_op.drop_index('ix_cf_recurring_user_active')

    op.drop_table('cashflow_recurring_payment')
    with op.batch_alter_table('cashflow_budget', schema=None) as batch_op:
        batch_op.drop_index('ix_cf_budget_user_month')

    op.drop_table('cashflow_budget')
    op.drop_table('user')
    # ### end Alembic commands ###
